import time
import threading

try:
    import pigpio
except Exception:
    pigpio = None

try:
    import RPi.GPIO as GPIO
except Exception:
    GPIO = None


class GPIOBuzzer:
    """Passive/active buzzer driver with hardware-PWM preference on GPIO18.

    A passive piezo sounds cleanest when the carrier itself is generated by
    hardware and Python only controls the start/stop envelope. GPIO18 is a
    hardware-PWM pin on the Pi 3B+.
    """

    def __init__(self, pin=18, passive=True, active_high=True):
        self.pin = int(pin)
        self.passive = bool(passive)
        self.active_high = bool(active_high)
        self.lock = threading.Lock()
        self.generation = 0
        self.pwm = None
        self.pi = None
        self.backend = "none"
        self.available = False

        if self.passive and pigpio is not None:
            try:
                pi = pigpio.pi()
                if pi.connected:
                    self.pi = pi
                    self.pi.set_mode(self.pin, pigpio.OUTPUT)
                    self.pi.hardware_PWM(self.pin, 0, 0)
                    self.backend = "pigpio"
                    self.available = True
                    return
                pi.stop()
            except Exception:
                self.pi = None

        if GPIO is None:
            return
        try:
            GPIO.setwarnings(False)
            GPIO.setmode(GPIO.BCM)
            GPIO.setup(self.pin, GPIO.OUT)
            if self.passive:
                self.pwm = GPIO.PWM(self.pin, 2700)
                self.pwm.start(0)
            else:
                GPIO.output(self.pin, GPIO.LOW if self.active_high else GPIO.HIGH)
            self.backend = "rpi_gpio"
            self.available = True
        except Exception:
            self.available = False

    def _tone_on_locked(self, frequency, duty):
        frequency = max(50, int(frequency))
        duty = max(1, min(99, int(duty)))
        if self.passive:
            if self.backend == "pigpio":
                # pigpio duty is 0..1,000,000. 50% gives the full alternating
                # swing a passive piezo expects, matching ESP32 LEDC behaviour.
                self.pi.hardware_PWM(self.pin, frequency, duty * 10000)
            else:
                self.pwm.ChangeDutyCycle(0)
                self.pwm.ChangeFrequency(frequency)
                self.pwm.ChangeDutyCycle(duty)
        else:
            GPIO.output(self.pin, GPIO.HIGH if self.active_high else GPIO.LOW)

    def _tone_off_locked(self):
        if self.passive:
            if self.backend == "pigpio":
                self.pi.hardware_PWM(self.pin, 0, 0)
            elif self.pwm is not None:
                self.pwm.ChangeDutyCycle(0)
        elif GPIO is not None:
            GPIO.output(self.pin, GPIO.LOW if self.active_high else GPIO.HIGH)

    def beep(self, frequency=2700, duration_ms=40, duty=50):
        """Start one clean tone burst.

        The carrier is continuous hardware PWM. A generation token guarantees
        that an older stop timer can never cut a newer beep short.
        """
        if not self.available:
            return
        with self.lock:
            self.generation += 1
            token = self.generation
            self._tone_off_locked()
            self._tone_on_locked(frequency, duty)
        threading.Thread(
            target=self._finish_beep,
            args=(token, max(1, int(duration_ms))),
            daemon=True,
        ).start()

    def _finish_beep(self, token, duration_ms):
        time.sleep(duration_ms / 1000.0)
        try:
            with self.lock:
                if token == self.generation:
                    self._tone_off_locked()
        except Exception:
            pass

    def off(self):
        if not self.available:
            return
        with self.lock:
            self.generation += 1
            try:
                self._tone_off_locked()
            except Exception:
                pass

    def close(self):
        if not self.available:
            return
        try:
            self.off()
            if self.pwm is not None:
                self.pwm.stop()
            if self.pi is not None:
                self.pi.stop()
            if self.backend == "rpi_gpio" and GPIO is not None:
                GPIO.cleanup(self.pin)
        except Exception:
            pass
