#!/usr/bin/env python3
"""Prove the RF Eye C2000 detector on known-truth synthetic captures.

No SDR, no antenna and no real transmission are involved.  Signals with known
ground truth are generated by ``rfeye.tetra_sim`` and pushed through the
production ``rfeye.tetra_phy`` verification path, so a regression in the
detector fails here instead of in the field.

Run with ``--table`` to print every measured score, which is how the
acceptance limits in ``tetra_phy.LIMITS`` were chosen.

    python3 scripts/tetra-phy-selftest.py
    python3 scripts/tetra-phy-selftest.py --table
"""
import argparse
import math
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "rfeye"))

import numpy as np                                              # noqa: E402

import tetra_phy as phy                                         # noqa: E402
import tetra_sim as sim                                         # noqa: E402

SR = 288_000.0          # 28.8 MHz / 100, and exactly 16 x the 18 kbaud rate
DECIM = 8               # -> 36 kHz channel baseband, 2 samples per symbol
DWELL_S = 262144 / SR   # 0.910 s, about 16 TDMA frames
OFFSET = -72_000.0      # channel position inside the dwell, away from the DC spike

ROWS = []
FAILURES = []


def _run(name, iq, role, expect):
    ch = phy.Channelizer(iq, SR)
    # full=True measures every quantity so the table stays informative even
    # for cases that production rejects on the first cheap check.
    r = phy.analyse(ch, OFFSET, role=role, freq_hz=380_012_500.0, full=True)
    # The shipping path stops at the first failure. Skipping work can only
    # ever hide *additional* failures, so the verdict must be identical --
    # assert it rather than assume it.
    fast = phy.analyse(ch, OFFSET, role=role, freq_hz=380_012_500.0)
    if fast.ok != r.ok:
        FAILURES.append(f"{name}: fail-fast path disagrees with full analysis "
                        f"({fast.reason} vs {r.reason})")
    ROWS.append((name, role, expect, r))
    if r.ok != expect:
        FAILURES.append(
            f"{name}: expected {'ACCEPT' if expect else 'REJECT'}, "
            f"got {'ACCEPT' if r.ok else 'REJECT'} ({r.reason})")
    return r


def _tetra(role, snr_db, seed=0, slot_pattern=(1,)):
    s = sim.tetra_carrier(DWELL_S, SR, role=role, seed=seed,
                          slot_pattern=slot_pattern, freq_offset_hz=OFFSET)
    return sim.make_capture([(s, 1.0)], DWELL_S, SR, snr_db=snr_db, seed=seed + 100)


def positives():
    # A base station downlink is continuous and is the network anchor.
    for snr in (30, 22, 16, 12):
        _run(f"downlink TETRA {snr} dB", _tetra("DOWNLINK", snr, seed=snr),
             "DOWNLINK", True)
    # A handset transmitting one slot per frame: this is "police nearby".
    for snr in (30, 22, 16, 12):
        _run(f"uplink TETRA 1 slot {snr} dB", _tetra("UPLINK", snr, seed=snr + 5),
             "UPLINK", True)
    # Two slots per frame, e.g. a higher rate bearer.
    _run("uplink TETRA 2 slots 20 dB",
         _tetra("UPLINK", 20, seed=41, slot_pattern=(0, 2)), "UPLINK", True)
    # A secondary traffic carrier is discontinuous: ETSI only requires the
    # main carrier to be transmitted continuously. Demanding near-100% duty
    # of a downlink would lock only the main carrier, and every call that
    # moved to a traffic carrier would go unwatched.
    for pattern, name in (((0, 2), "half"), ((1,), "quarter")):
        _run(f"downlink TETRA traffic carrier, {name} duty",
             _tetra("UPLINK", 22, seed=51, slot_pattern=pattern),
             "DOWNLINK", True)
    # Uncorrected RTL-SDR crystal error: 2.5 kHz is roughly 6.6 ppm at 380 MHz.
    s = sim.tetra_carrier(DWELL_S, SR, role="UPLINK", seed=61,
                          freq_offset_hz=OFFSET + 2500.0)
    _run("uplink TETRA +2.5 kHz tuner error",
         sim.make_capture([(s, 1.0)], DWELL_S, SR, snr_db=20, seed=161),
         "UPLINK", True)
    # A busy site: neighbouring 25 kHz carriers must not break the target.
    tgt = sim.tetra_carrier(DWELL_S, SR, role="UPLINK", seed=71, freq_offset_hz=OFFSET)
    n1 = sim.tetra_carrier(DWELL_S, SR, role="DOWNLINK", seed=72, freq_offset_hz=OFFSET + 25000.0)
    n2 = sim.tetra_carrier(DWELL_S, SR, role="DOWNLINK", seed=73, freq_offset_hz=OFFSET - 25000.0)
    _run("uplink TETRA with both neighbours active",
         sim.make_capture([(tgt, 1.0), (n1, 1.0), (n2, 1.0)], DWELL_S, SR,
                          snr_db=22, seed=171), "UPLINK", True)


def negatives():
    empty = sim.make_capture([], DWELL_S, SR, seed=201)
    _run("noise only", empty, "UPLINK", False)
    _run("noise only (downlink role)", empty, "DOWNLINK", False)

    _run("CW spur",
         sim.make_capture([(sim.cw_tone(DWELL_S, SR, OFFSET), 1.0)],
                          DWELL_S, SR, snr_db=35, seed=202), "DOWNLINK", False)

    _run("broadband clutter 250 kHz",
         sim.make_capture([(sim.band_noise(DWELL_S, SR, 250_000.0, 0.0, 203), 1.0)],
                          DWELL_S, SR, snr_db=25, seed=203), "UPLINK", False)

    # The v7 field failure: one wide hump lighting up several adjacent
    # 25 kHz raster channels at once.
    _run("wide hump across 3 raster channels",
         sim.make_capture([(sim.band_noise(DWELL_S, SR, 70_000.0, OFFSET, 204), 1.0)],
                          DWELL_S, SR, snr_db=25, seed=204), "UPLINK", False)

    # Right bandwidth, right duty cycle, wrong physics.  Profile v7 could not
    # separate this from a handset; the symbol-rate test does it instantly.
    _run("gated narrowband noise, TETRA-like duty",
         sim.make_capture([(sim.gated_noise(DWELL_S, SR, 22_000.0, 0.0142,
                                            0.0567, OFFSET, 205), 1.0)],
                          DWELL_S, SR, snr_db=25, seed=205), "UPLINK", False)
    # Same, but deliberately also on the exact TETRA frame period.
    _run("gated noise on the TETRA frame grid",
         sim.make_capture([(sim.gated_noise(DWELL_S, SR, 22_000.0, phy.SLOT_S,
                                            phy.FRAME_S, OFFSET, 206), 1.0)],
                          DWELL_S, SR, snr_db=25, seed=206), "UPLINK", False)

    _run("narrowband FM voice",
         sim.make_capture([(sim.nfm_voice(DWELL_S, SR, 2500.0, 900.0, OFFSET), 1.0)],
                          DWELL_S, SR, snr_db=28, seed=207), "DOWNLINK", False)

    _run("4800 baud 2-FSK data",
         sim.make_capture([(sim.fsk_data(DWELL_S, SR, 4800.0, 4500.0, OFFSET, 208), 1.0)],
                          DWELL_S, SR, snr_db=28, seed=208), "DOWNLINK", False)

    # A coherent spur comb, the RTL-SDR artefact profile v7 needed a special
    # rejector for.  Here it simply is not TETRA.
    comb = [(sim.cw_tone(DWELL_S, SR, OFFSET + k * 25_000.0), 1.0)
            for k in (-2, -1, 0, 1, 2)]
    _run("coherent spur comb",
         sim.make_capture(comb, DWELL_S, SR, snr_db=30, seed=209), "UPLINK", False)

    # A real TETRA downlink is continuous, so it must not be mistaken for a
    # handset transmitting next to you.  Role separation matters: this is the
    # difference between "a mast exists somewhere" and "police are here".
    _run("continuous TETRA judged as uplink",
         _tetra("DOWNLINK", 25, seed=210), "UPLINK", False)

    # The hardest adversary: same modulation family, same order of bandwidth,
    # wrong symbol rate.  Nothing but the rate selectivity test rejects these,
    # so they are the proof that it earns its place.
    for baud in (15300.0, 21700.0, 16000.0):
        _run(f"pi/4-DQPSK at {baud:.0f} baud (not TETRA)",
             sim.make_capture([(sim.dqpsk_carrier(DWELL_S, SR, baud, 212,
                                                  OFFSET), 1.0)],
                              DWELL_S, SR, snr_db=28, seed=212), "DOWNLINK", False)

    _run("DMR 4-FSK 4800 baud",
         sim.make_capture([(sim.fsk4_data(DWELL_S, SR, 4800.0, 1944.0,
                                          OFFSET, 213), 1.0)],
                          DWELL_S, SR, snr_db=28, seed=213), "DOWNLINK", False)

    _run("ignition impulse noise",
         sim.make_capture([(sim.impulse_noise(DWELL_S, SR, 140.0, 6e-5,
                                              OFFSET, 214), 1.0)],
                          DWELL_S, SR, snr_db=28, seed=214), "UPLINK", False)

    # Too weak to verify.  Refusing to guess is the correct behaviour.
    _run("uplink TETRA 4 dB (below verification floor)",
         _tetra("UPLINK", 4, seed=211), "UPLINK", False)


def rate_selectivity_sanity():
    """The symbol-rate test must peak at 18 kbaud and nowhere else."""
    iq = _tetra("DOWNLINK", 25, seed=301)
    ch = phy.Channelizer(iq, SR)
    bb, rate = ch.extract(OFFSET, DECIM)
    scores = {b: phy.dqpsk_metric(bb, rate, b)
              for b in (phy.SYMBOL_RATE_HZ,) + phy.DECOY_BAUDS}
    best = max(scores, key=scores.get)
    if abs(best - phy.SYMBOL_RATE_HZ) > 1.0:
        FAILURES.append(
            f"symbol-rate peak at {best:.0f} baud, expected 18000 "
            f"({ {int(k): round(v, 3) for k, v in scores.items()} })")
    return scores


def constants_sanity():
    checks = [
        ("slot", phy.SLOT_S, 255 / 18000.0),
        ("frame", phy.FRAME_S, 4 * 255 / 18000.0),
        ("multiframe", phy.MULTIFRAME_S, 18 * 4 * 255 / 18000.0),
        ("frame rate", phy.FRAME_RATE_HZ, 18000.0 / (4 * 255)),
    ]
    for name, got, want in checks:
        if abs(got - want) > 1e-9:
            FAILURES.append(f"constant {name}: {got} != {want}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--table", action="store_true",
                    help="print every measured score")
    args = ap.parse_args()

    constants_sanity()
    positives()
    negatives()
    scores = rate_selectivity_sanity()

    if args.table:
        print(f"dwell {DWELL_S:.3f} s @ {SR/1e3:.0f} kS/s, channel at "
              f"{OFFSET/1e3:+.0f} kHz, {phy.SYMBOL_RATE_HZ/1e3:.0f} kbaud\n")
        hdr = (f"{'case':<44}{'role':<9}{'want':<7}{'got':<7}"
               f"{'snr':>6}{'bw':>7}{'bnd':>6}{'flat':>6}"
               f"{'dqpsk':>7}{'4ph':>6}{'sel':>6}{'frame':>7}{'duty':>6}{'slot':>6}")
        print(hdr)
        print("-" * len(hdr))
        for name, role, expect, r in ROWS:
            print(f"{name:<44}{role:<9}"
                  f"{'ACC' if expect else 'REJ':<7}{'ACC' if r.ok else 'REJ':<7}"
                  f"{r.snr_db:6.1f}{r.occupied_bw_hz/1e3:7.1f}"
                  f"{r.boundary_reject_db:6.1f}{r.flatness_db:6.1f}"
                  f"{r.dqpsk_m:7.3f}{r.dqpsk_phase_spread:6.2f}{r.dqpsk_selectivity:6.1f}"
                  f"{r.frame_line_ratio:7.1f}{r.duty:6.2f}{r.slot_quantisation:6.2f}")
            if not r.ok and expect:
                print(f"{'':<44}-> {r.reason}")
        print("\nsymbol-rate scan on a clean downlink:")
        for b in sorted(scores):
            mark = "  <- TETRA" if abs(b - phy.SYMBOL_RATE_HZ) < 1 else ""
            print(f"  {b:8.0f} baud  m4 = {scores[b]:.3f}{mark}")
        print()

    print(f"{len(ROWS)} cases, {len(FAILURES)} failures")
    for f in FAILURES:
        print("  FAIL " + f)
    if FAILURES:
        return 1
    print("tetra-phy-selftest OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
